config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'destroy', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  validates :title, presence: true,
            length: { minimum:3, maximum: 30 }
  validates :description, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_RAGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 25 },
                    format: { with: VALID_EMAIL_RAGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :currentUser, :logged_in?
  def currentUser
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!currentUser
  end

  def require_user
    if !logged_in? && currentUser.admin?
      flash[:alert] = "You must be log in"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show , :update, :edit, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:update,:edit, :destroy]

  def show; end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(param)
    @article.user = currentUser
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(param)
      flash[:notice] = 'Article was updated successfully'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def param
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if currentUser != @article.user && !  currentUser.admin?
      flash[:alert] = 'You must be same user to perform this action '
      redirect_to articles_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 4)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You are Logged in"
      redirect_to user_path(user)
    else
      flash.now[:alert] = "The username and password is incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update,:destroy]
  before_action :require_same_user, only: [:update,:edit,:destroy]

  def new
    @user = User.new
  end

  def set_user
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}, You are successfully sign up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:username, :email, :password))
      flash[:notice] = "#{@user.username} updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles
  end

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if currentUser == @user
    flash[:alert] = 'Account and articles deleted permanently'
    redirect_to root_path
  end

  private

  def require_same_user
    if currentUser != @user && !currentUser.admin?
      flash[:alert] = 'You must be same user to perform this action '
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container">
  <h2 class="text-center ">Articles</h2>
  <% @articles.each do |article| %>
    <div class="card text-center m-5 shadow mb-5 bg-white rounded">
      <div class="card-header">
        <%if article.user %>
          Created by <%= link_to article.user.username, user_path(article.user)  %>
        <%end%><br>
        <% if article.categories.any? %>
        <%= render article.categories %>
        <%end %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= article.title %></h5>
        <p class="card-text"><%= article.description %></p>
        <%= link_to 'Show' , article_path(article),class: "btn btn-outline-primary" %>
        <% if logged_in? && (currentUser == article.user || currentUser.admin?)%>
        <%= link_to 'Edit' , edit_article_path(article) , class: "btn btn-outline-success"%>
        <%= link_to 'Delete' , article_path(article) , method: :delete, data: {confirm: "Are you sure"} , class: "btn btn-outline-danger"%>
          <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(article.created_at) %> ago,
          edited <%= time_ago_in_words(article.updated_at) %> ago</small>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center m-3">
    <%= link_to 'Create new article', new_article_path ,class: "btn btn-success"%>
  </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/error', obj:@article%>
<%= form_with(model: @article ,local: true) do |f| %>

  <p>
    <%= f.label :title  %><br>
    <%= f.text_field :title%>
  </p>
  <p>
    <%= f.label :description  %><br>
    <%= f.text_area :description%>
  </p>
  <p>
    <%= f.label :Category  %><br>
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
                            { prompt: "Make your selection from the list below (can be empty)"},
                            { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
  </p>
  <p>
    <%= f.submit class: "btn btn-success" %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Update article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles' %>
<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div class="justify-content-center m-5">
  <div class="container">
    <h1>Create a new article</h1>
    <%= render 'form' %>
    <%= link_to 'Return to articles listing', articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h2 class="text-center m-5"><%= @article.title %></h2>
  <div class="card text-center m-5 shadow mb-5 bg-white rounded">
      <div class="card-header">
        <%if @article.user %>
          Created by <%= link_to @article.user.username, user_path(@article.user)  %>
        <%end%>
        <% if @article.categories.any? %>
          <div class="mt-2"><%= render @article.categories %></div>
        <%end %>
      </div>
      <div class="card-body">
        </h5>
        <div class="card-text"><%=simple_format(@article.description)  %></div>
        <% if logged_in? && @article.user == currentUser %>
        <%= link_to 'Edit' , edit_article_path(@article) , class: "btn btn-outline-success"%>
        <%= link_to 'Delete' , article_path(@article) , method: :delete, data: {confirm: "Are you sure"} , class: "btn btn-outline-danger"%>
          <%end %>
        <%= link_to 'Return to Articles' , articles_path,class: "btn btn-outline-primary" %>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
      </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container m-5 justify-content-center" id="signUp">
  <%= render 'shared/error', obj: @category %>
  <div class="signup-form">
    <%= form_with(model: @category ,local: true , class:"shadow p-3 mb-3 bg-info rounded") do |f| %>
      <div class="col-xs-8 col-xs-offset-4">
        <h2>Edit Category</h2>
      </div>
      <div class="form-group">
        <%= f.label :name,'Category name', class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.text_field :name, class:"form-control", required:"required", placeholder:"Enter name"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

</div>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="apple_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago,
              edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="apple_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<div class="container m-5 justify-content-center" id="signUp">
  <%= render 'shared/error', obj: @category %>
  <div class="signup-form">
    <%= form_with(model: @category ,local: true , class:"shadow p-3 mb-3 bg-info rounded") do |f| %>
      <div class="col-xs-8 col-xs-offset-4">
        <h2>Create Category</h2>
      </div>
      <div class="form-group">
        <%= f.label :name,'Category name', class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.text_field :name, class:"form-control", required:"required", placeholder:"Enter name"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<%= render 'articles/articles' %>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Home' , root_path , class: "navbar-brand", id: "logo"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Articles' , articles_path , class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Users' , users_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to 'About' ,about_path , class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && currentUser.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item" id="logout">
          <%=link_to !currentUser.admin? ? currentUser.username : "[admin]#{currentUser.username}" ,user_path(currentUser), class: "nav-link" %>
        </li>
        <li class="nav-item" id="logout">
          <%=link_to 'Logout' ,destroy_path, class: "nav-link", method: :delete %>
        </li>
      <%end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="container p-5 text-center">About Page</h1>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Articles</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to 'sign Up', signup_path, class:"btn btn-success btn-lg" %>
      <%= link_to 'Log in', login_path, class:"btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<%if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="alert-heading">The following errors are preventing the article to save</h4>
    <ul>
      <%obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white fixed-bottom">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/users/_form.html.erb
<div class="container m-5">
  <%= render 'shared/error', obj: @user %>
  <div class="signup-form">
    <%= form_with(model: @user ,local: true , class:"form-horizontal") do |f| %>
      <div class="col-xs-8 col-xs-offset-4">
        <h2>Sign Up</h2>
      </div>
      <div class="form-group">
        <%= f.label :username, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.text_field :username, class:"form-control", required:"required"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.email_field :email, class:"form-control", required:"required"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.password_field :password, class:"form-control", required:"required"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-success" %>
      </div>
      </form>
      <div class="text-center">Already have an account? <a href="#">Login here</a></div>
    <% end %>
  </div>

</div>

app/views/users/edit.html.erb
<%= render 'form'%>

app/views/users/index.html.erb
 <div id="users" class=" justify-content-center">
    <h1>All users</h1>
    <% @users.each do |user| %>
      <div class="container m-5" >
        <div class="card" style="width: 18rem;">
          <%= image_tag "dp.png", alt:"User image" ,height: 250%>
          <div class="card-body">
            <h5 class="card-title"><%= user.username %></h5>
            <p class="card-text"><%= user.email %></p>
            <p class="card-text">Joined <%= time_ago_in_words(user.created_at) %> ago</p>
            <div class="row">
              <div class="col align-self-start">
                <%= link_to "view", user_path(user), class:"btn btn-success"  %>
              </div>
              <div class="col align-self-end">
                <% if currentUser && currentUser.admin? %>
                  <%= link_to "delete", user_path(user), class:"btn btn-danger", id: "deleteUser", data: {confirm: "Are you sure you want to delete"}, method: :delete %>
                <%end %>
              </div>
            </div>

          </div>
        </div>
      </div>
    <%end %>
  </div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1 style="text-align: center"><%=@user.username %></h1>
<div class="text-center mt-4">
  <%if @user==currentUser %>
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  <%end %>
  <%= link_to "delete Profile", user_path(@user),method: :delete,data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger m-3" %>
</div>
<%= render 'articles/articles' %>